# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from human_api.models.base_model_ import Model
from human_api import util


class BoolDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, success: bool=None):  # noqa: E501
        """BoolDataResponse - a model defined in Swagger

        :param success: The success of this BoolDataResponse.  # noqa: E501
        :type success: bool
        """
        self.swagger_types = {
            'success': bool
        }

        self.attribute_map = {
            'success': 'success'
        }
        self._success = success

    @classmethod
    def from_dict(cls, dikt) -> 'BoolDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bool_data_response of this BoolDataResponse.  # noqa: E501
        :rtype: BoolDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this BoolDataResponse.


        :return: The success of this BoolDataResponse.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this BoolDataResponse.


        :param success: The success of this BoolDataResponse.
        :type success: bool
        """

        self._success = success
