# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from human_api.models.base_model_ import Model
from human_api import util


class ErrorNotexistResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error: str = None):  # noqa: E501
        """ErrorNotexistResponse - a model defined in Swagger

        :param error: The error of this ErrorNotexistResponse.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {'error': str}

        self.attribute_map = {'error': 'error'}
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorNotexistResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_notexist_response of this ErrorNotexistResponse.  # noqa: E501
        :rtype: ErrorNotexistResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this ErrorNotexistResponse.


        :return: The error of this ErrorNotexistResponse.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this ErrorNotexistResponse.


        :param error: The error of this ErrorNotexistResponse.
        :type error: str
        """

        self._error = error
