# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from human_api.models.base_model_ import Model
from human_api import util


class ErrorParameterResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error: str = None, parameter_name: str = None):  # noqa: E501
        """ErrorParameterResponse - a model defined in Swagger

        :param error: The error of this ErrorParameterResponse.  # noqa: E501
        :type error: str
        :param parameter_name: The parameter_name of this ErrorParameterResponse.  # noqa: E501
        :type parameter_name: str
        """
        self.swagger_types = {'error': str, 'parameter_name': str}

        self.attribute_map = {'error': 'error', 'parameter_name': 'parameter_name'}
        self._error = error
        self._parameter_name = parameter_name

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorParameterResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_parameter_response of this ErrorParameterResponse.  # noqa: E501
        :rtype: ErrorParameterResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this ErrorParameterResponse.


        :return: The error of this ErrorParameterResponse.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this ErrorParameterResponse.


        :param error: The error of this ErrorParameterResponse.
        :type error: str
        """

        self._error = error

    @property
    def parameter_name(self) -> str:
        """Gets the parameter_name of this ErrorParameterResponse.


        :return: The parameter_name of this ErrorParameterResponse.
        :rtype: str
        """
        return self._parameter_name

    @parameter_name.setter
    def parameter_name(self, parameter_name: str):
        """Sets the parameter_name of this ErrorParameterResponse.


        :param parameter_name: The parameter_name of this ErrorParameterResponse.
        :type parameter_name: str
        """

        self._parameter_name = parameter_name
