# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from human_api.models.base_model_ import Model
from human_api import util


class JobCreateBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self,
                 gas_payer: str = None,
                 gas_payer_private: str = None,
                 factory_address: str = None,
                 rep_oracle_pub: str = None,
                 manifest_url: str = None,
                 network_id: int = 0):  # noqa: E501
        """JobCreateBody - a model defined in Swagger

        :param gas_payer: The gas_payer of this JobCreateBody.  # noqa: E501
        :type gas_payer: str
        :param gas_payer_private: The gas_payer_private of this JobCreateBody.  # noqa: E501
        :type gas_payer_private: str
        :param factory_address: The factory_address of this JobCreateBody.  # noqa: E501
        :type factory_address: str
        :param rep_oracle_pub: The rep_oracle_pub of this JobCreateBody.  # noqa: E501
        :type rep_oracle_pub: str
        :param manifest_url: The manifest_url of this JobCreateBody.  # noqa: E501
        :type manifest_url: str
        :param network_id: The network_id of this JobCreateBody.  # noqa: E501
        :type network_id: int
        """
        self.swagger_types = {
            'gas_payer': str,
            'gas_payer_private': str,
            'factory_address': str,
            'rep_oracle_pub': str,
            'manifest_url': str,
            'network_id': int
        }

        self.attribute_map = {
            'gas_payer': 'gasPayer',
            'gas_payer_private': 'gasPayerPrivate',
            'factory_address': 'factoryAddress',
            'rep_oracle_pub': 'repOraclePub',
            'manifest_url': 'manifestUrl',
            'network_id': 'networkId'
        }
        self._gas_payer = gas_payer
        self._gas_payer_private = gas_payer_private
        self._factory_address = factory_address
        self._rep_oracle_pub = rep_oracle_pub
        self._manifest_url = manifest_url
        self._network_id = network_id

    @classmethod
    def from_dict(cls, dikt) -> 'JobCreateBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The job_create_body of this JobCreateBody.  # noqa: E501
        :rtype: JobCreateBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gas_payer(self) -> str:
        """Gets the gas_payer of this JobCreateBody.


        :return: The gas_payer of this JobCreateBody.
        :rtype: str
        """
        return self._gas_payer

    @gas_payer.setter
    def gas_payer(self, gas_payer: str):
        """Sets the gas_payer of this JobCreateBody.


        :param gas_payer: The gas_payer of this JobCreateBody.
        :type gas_payer: str
        """

        self._gas_payer = gas_payer

    @property
    def gas_payer_private(self) -> str:
        """Gets the gas_payer_private of this JobCreateBody.


        :return: The gas_payer_private of this JobCreateBody.
        :rtype: str
        """
        return self._gas_payer_private

    @gas_payer_private.setter
    def gas_payer_private(self, gas_payer_private: str):
        """Sets the gas_payer_private of this JobCreateBody.


        :param gas_payer_private: The gas_payer_private of this JobCreateBody.
        :type gas_payer_private: str
        """

        self._gas_payer_private = gas_payer_private

    @property
    def factory_address(self) -> str:
        """Gets the factory_address of this JobCreateBody.


        :return: The factory_address of this JobCreateBody.
        :rtype: str
        """
        return self._factory_address

    @factory_address.setter
    def factory_address(self, factory_address: str):
        """Sets the factory_address of this JobCreateBody.


        :param factory_address: The factory_address of this JobCreateBody.
        :type factory_address: str
        """

        self._factory_address = factory_address

    @property
    def rep_oracle_pub(self) -> str:
        """Gets the rep_oracle_pub of this JobCreateBody.


        :return: The rep_oracle_pub of this JobCreateBody.
        :rtype: str
        """
        return self._rep_oracle_pub

    @rep_oracle_pub.setter
    def rep_oracle_pub(self, rep_oracle_pub: str):
        """Sets the rep_oracle_pub of this JobCreateBody.


        :param rep_oracle_pub: The rep_oracle_pub of this JobCreateBody.
        :type rep_oracle_pub: str
        """

        self._rep_oracle_pub = rep_oracle_pub

    @property
    def manifest_url(self) -> str:
        """Gets the manifest_url of this JobCreateBody.


        :return: The manifest_url of this JobCreateBody.
        :rtype: str
        """
        return self._manifest_url

    @manifest_url.setter
    def manifest_url(self, manifest_url: str):
        """Sets the manifest_url of this JobCreateBody.


        :param manifest_url: The manifest_url of this JobCreateBody.
        :type manifest_url: str
        """

        self._manifest_url = manifest_url

    @property
    def network_id(self) -> int:
        """Gets the network_id of this JobCreateBody.


        :return: The network_id of this JobCreateBody.
        :rtype: int
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id: int):
        """Sets the network_id of this JobCreateBody.


        :param network_id: The network_id of this JobCreateBody.
        :type network_id: int
        """

        self._network_id = network_id
