# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from human_api.models.base_model_ import Model
from human_api import util


class StringDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: str=None):  # noqa: E501
        """StringDataResponse - a model defined in Swagger

        :param data: The data of this StringDataResponse.  # noqa: E501
        :type data: str
        """
        self.swagger_types = {
            'data': str
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'StringDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The string_data_response of this StringDataResponse.  # noqa: E501
        :rtype: StringDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> str:
        """Gets the data of this StringDataResponse.


        :return: The data of this StringDataResponse.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this StringDataResponse.


        :param data: The data of this StringDataResponse.
        :type data: str
        """

        self._data = data
